"""invoices table

Revision ID: 072a3747ea6d
Revises: 
Create Date: 2019-12-28 16:39:41.163364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072a3747ea6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('invoice', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('suma', sa.Float(), nullable=True),
    sa.Column('pvm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    # ### end Alembic commands ###
